print ("Hello world!")
print ("Hello Again")
print ("I like typing this.")
print ("This is fun.")
print ('Yay! Printing')
print ("I'd much rather you 'not'.")
print ('I "said" do not touch this.')

print ("Seokhyeon Choi")
print ("2016 03 09 19:49")
print ("Lee Se Dol:Apa Go = 0:1")